### ISSUE TITLE
Add new GTFS data for holiday exceptions

### ISSUE THREAD

**Issue by brendanbabb** [codeforanchorage/realtime-bus-sms#103]
Get the No Service on a holiday message to respond on future holidays.

**Comment by cd-Hippo** [comment]
Is the idea to automate this process, or copy over dates from http://gtfs.muni.org/People_Mover.gtfs.zip manually?

**Comment by markmeyerphoto** [comment]
@cd-Hippo there's a branch that's working but still needs a few tweaks that automatically downloads the zip file on a cron-like schedule, unpacks it, and updates the data here: https://github.com/codeforanchorage/realtime-bus-sms/tree/updateGTFS

One of the questions we had last time we talked about it was, what GTFS data should be in the repository and what should happen if there's no data when the app starts?

**Comment by markmeyerphoto** [comment]
The Holiday Schedule should now update when there is new GTFS.
