### ISSUE TITLE
Cookies don't work on Facebook Messaging

### ISSUE THREAD

**Issue by tescher** [codeforanchorage/realtime-bus-sms#109]
Breaks the knock knock jokes, and maybe some other things. Find a way to keep state between FB messages from the same person.

**Comment by brendanbabb** [comment]
We are ok with that

**Comment by tescher** [comment]
We might be able to do a cookie-like thing since we know the message
sender. Would need to be on the server side.

Tim Escher
tim@eschers.com
608-432-5799
