### ISSUE TITLE
Exclude ELB traffic from the logs AND log the proper IP

### ISSUE THREAD

**Issue by NigelKibodeaux** [codeforanchorage/realtime-bus-sms#110]
ELB health check requests have this header: `'user-agent': 'ELB-HealthChecker/2.0'`

use the `'x-forwarded-for'` header to determine the real IP of the requester.

**Comment by markmeyerphoto** [comment]
Hey @NigelKibodeaux. I think PR #111 fixes this. I'm not sure what's going on with the Travis check — it passes tests locally. It looks like it's failing on a FB test that is unrelated to my changes.

**Comment by markmeyerphoto** [comment]
Also one question: This sets the 'trust proxy' setting in express to 'true' which allows us to grab the correct client ip address. Do you know if there are any negative consequences of setting the trust setting to 'true' rather than specifying a range of trusted proxy ip addresses?

**Comment by NigelKibodeaux** [comment]
I can't think of any negative consequences. I suppose someone could make a request with their own `'x-forwarded-for'` header and, assuming the ELB doesn't overwrite it, we would believe them about their fake IP.

**Comment by brendanbabb** [comment]
Fixed in #111
