### ISSUE TITLE
FB Messenger isn't responding to bus requests

### ISSUE THREAD

**Issue by brendanbabb** [codeforanchorage/realtime-bus-sms#112]
When you FB Messenger with When's the bus? CFA in Facebook it seems to send the messages but I didn't get a response. Not sure if recent fixes to the Google logging changed this.

**Comment by markmeyerphoto** [comment]
I don't think this is because of the recent change — it was only a small change to the logging, but I'll double check.

**Comment by brendanbabb** [comment]
This was fixed by Tim.
