### ISSUE TITLE
GTFS auto - updates vs git repo

### ISSUE THREAD

**Issue by markmeyerphoto** [codeforanchorage/realtime-bus-sms#129]
Since we have started automatically updating GTFS, it has become a little inconvenient to deal with GTFS files in the git repo. Here's what now happens:

1. Clone repo locally
2. This includes the GTFS files, but they often old
3. The app downloads new GTFS zip file and expands contents
4. Local repo now shows changed files - to do anything like make a new branch, we need to either stash or commit these changes.

So at this point do we just commit the new files? This makes for some big commits with a lot of changes that we don't actually control.

Would it be better to add the gtfs directory to .gitignore?

**Comment by tescher** [comment]
I vote for .gitignore

Tim Escher
tim@eschers.com
608-432-5799

**Comment by markmeyerphoto** [comment]
Changed in the last pull. GTFS is no longer in the repo.
