### ISSUE TITLE
Let's get a domain

### ISSUE THREAD

**Issue by NigelKibodeaux** [codeforanchorage/realtime-bus-sms#16]
Maybe something with "Anchorage" and "Bus" in it?

**Comment by brendanbabb** [comment]
I created this a few weeks ago but haven't looked up how to make port 8080 the default. http://buses.codeforanchorage.org:8080/

**Comment by NigelKibodeaux** [comment]
I can do that. It's a server configuration thing.

**Comment by brendanbabb** [comment]
I can come up with a better name as well in the form of name.codeforanchorage.org if that will work.

Takes about a day to propagate.

**Comment by NigelKibodeaux** [comment]
Ok, now http://buses.codeforanchorage.org works without the port 8080

**Comment by NigelKibodeaux** [comment]
How about bus.codeforanchorage.org?

**Comment by brendanbabb** [comment]
Submitted bus.codeforanchorage.org to point to IP. Might take a few hours to cycle through.

**Comment by NigelKibodeaux** [comment]
Thanks!

**Comment by NigelKibodeaux** [comment]
Matti says ancbus.com

**Comment by NigelKibodeaux** [comment]
We decided to stick with bus.codeforanchorage.org for now
