### ISSUE TITLE
Implement logging

### ISSUE THREAD

**Issue by NigelKibodeaux** [codeforanchorage/realtime-bus-sms#2]
Let's collect some logs and statistics so we can track errors and get insight into how people are using the service.

**Comment by thermokarst** [comment]
+1

**Comment by NigelKibodeaux** [comment]
Hey bus people, I took a first step toward this. You can see the log at http://buses.codeforanchorage.org/db.json

It's not much to look at, but we can parse it and display it somehow in the future. One concern: I don't know how scalable this flat file database is.

I'm using https://github.com/typicode/lowdb which should make it easy to query, on the server or client side.

**Comment by brendanbabb** [comment]
Looks great! I submitted the request to move the Twilio number to the CfA
subaccount now that we have a kind of logging we can check.

We will still be able to see the Twilio logs from the sub account on CfA
using curl.

How hard would it be to include latitude and longitude information either
from the stop location if they do Bus Stop ID or from the resulting geocode
when they submit an address?

It might be interesting to plot requests on a map as they come in in
semi-real time in the future.

**Comment by NigelKibodeaux** [comment]
Don't we have a lookup for the lat/long of each bus stop? I'm thinking we
could associate those as part of the reporting process.

**Comment by hansthompson** [comment]
Can I suggest we close this issue and add comments to https://github.com/codeforanchorage/bus-request-loggeR?

**Comment by brendanbabb** [comment]
Sounds good

**Comment by brendanbabb** [comment]
Can we change the JSON order to most recent date to oldest date so you can see new log entries at the top of the screen? Then close this issue.

**Comment by NigelKibodeaux** [comment]
Ok, this is a little easier to read http://bus.codeforanchorage.org/log.html
