### ISSUE TITLE
add the web address to sms replies

### ISSUE THREAD

**Issue by NigelKibodeaux** [codeforanchorage/realtime-bus-sms#26]
but only if the reply leaves enough room for it to fit into 140 characters

**Comment by brendanbabb** [comment]
The limit for the texts are 160 characters, and if we can fit into that limit that lowers the costs. But are costs per month will be low as we grow, so it might make sense to include it as we start out and get charged for two texts, and then as the texting users grow to a certain point only include the web address for shorter messages or every 3rd message. https://www.twilio.com/help/faq/sms/how-much-does-it-cost-to-send-a-message-with-more-than-160-characters
