### ISSUE TITLE
Use "about" for info

### ISSUE THREAD

**Issue by NigelKibodeaux** [codeforanchorage/realtime-bus-sms#28]
Let's also send this when we get an error

**Comment by brendanbabb** [comment]
The reserved words for TWILIO are HELP and INFO [https://www.twilio.com/help/faq/sms/does-twilio-support-stop-block-and-cancel-aka-sms-filtering](https://www.twilio.com/help/faq/sms/does-twilio-support-stop-block-and-cancel-aka-sms-filtering) but we can use ABOUT.

We can have simple directions and a short link to codeforanchorage and/or the web version. We can advertise to have people text ABOUT to the number to learn how to use it.

**Comment by NigelKibodeaux** [comment]
done!
