### ISSUE TITLE
Implement simple web interface

### ISSUE THREAD

**Issue by NigelKibodeaux** [codeforanchorage/realtime-bus-sms#4]
Smartphone users might want to use this. Plus, it'll make testing free since we won't have to pay for text messages.

**Comment by redcap3000** [comment]
I'm working on this using meteor ... it has a very simple way to deploy to mobile via phonegap (android,ios) but will primarily be concentrating on a mobile-web face

http://rtanchor.meteor.com/

**Comment by brendanbabb** [comment]
I didn't really go over what exists for Anchorage buses. There is a text version of bustracker.muni.org that you can access on your smartphone but it is a little challenging to navigate. http://bustracker.muni.org/InfoPoint/noscript.aspx

Moovit is currently consuming the GTFS and has some trip planning. http://www.moovitapp.com/

I think there are at least 3+ potential apps here and am open to other ideas, just ideas I had in terms of being able to do phased roll outs. The simplest is just using a browser on mobile to hit a webpage and type in the bus stop id. This was accomplished with the Express set up by Nigel, and then enhancements this weekend by Mike, Jessica, and Ronaldo. If got a nice URL we can point them to this page: http://52.10.18.209:8080/ Plus some error messages and I think this could be good to go. 

The second could use GPS on your phone to show in colored text the bus stops close by and the next buses coming to them in realtime. Similar to an app from Chicago, http://etachicago.com/ Type in main avenue for the address. Also Transitapp.com I think is looking for realtime info and we are semi-far up on their wishlist (#10) of cities to come to next.

And the third could involve a map that shows you on the map and where the stops are and what times buses are arriving there next. Mike raised a good question of what do bus users actually want, and Jessica made a great suggestion of putting different types of traveler scenarios in the readme.

Sorry, I meant to cover some of this over the weekend, and in hindsight we could have used the conference room to go over current apps and uses cases. Excited about all the progress made this weekend. (This probably isn't the proper form for a github comment)

**Comment by NigelKibodeaux** [comment]
@redcap3000 We've accomplished what I intended in this ticket (_simple_ web interface) so I'm going to close this ticket but keep going on what you're doing!
