### ISSUE TITLE
email feedback

### ISSUE THREAD

**Issue by NigelKibodeaux** [codeforanchorage/realtime-bus-sms#44]
- [x] create address @codeforanchorage.org 
- [ ] set up forwarding to some peeps
- [ ] write the code to send email
  - [ ] use some gmail npm module probably
  - [ ] figure out how to store gmail credentials on server but not in repo

**Comment by brendanbabb** [comment]
Created bus_feedback@codeforanchorage.org that forwards to myself currently.

**Comment by brendanbabb** [comment]
bus_feedback@codeforanchorage.org exists now in Google Apps and just goes to me. We can set up the automailer now to it. But again not sure how we respond to the individual if they have a question.

**Comment by NigelKibodeaux** [comment]
I guess they would have to leave contact info in the message. Oh! Actually
we should put their # in the message if they do it through SMS. And we
could specify on the web to include contact info if they want a response.

**Comment by NigelKibodeaux** [comment]
replaced with sending the messages to a slack channel
