### ISSUE TITLE
Show when buses aren't running because of holidays

### ISSUE THREAD

**Issue by brendanbabb** [codeforanchorage/realtime-bus-sms#47]
Use the calendar file to see when holidays when buses don't run and display an appropriate message.

**Comment by tescher** [comment]
Do you have something that says what the different columns in the calendar file refer to?

**Comment by brendanbabb** [comment]
It is in calendar.txt which we can add into the raw GTFS folder. If the date has a 1 after it, then it is a holiday with no bus service. 

Here is what it looks like. 

service_id,date,exception_type
1,20150703,2
2,20150703,1
2,20150704,2
1,20150907,2
1,20151126,2
1,20151224,2
91,20151224,1
1,20151225,2
1,20160101,2
1,20160530,2
1,20160704,2
