### ISSUE TITLE
Had to install nodemailer manually on AWS deploy

### ISSUE THREAD

**Issue by brendanbabb** [codeforanchorage/realtime-bus-sms#51]

**Comment by tescher** [comment]
That was part of the pull request. Is there another method?

**Comment by brendanbabb** [comment]
My bad. Ignore.

**Comment by hansthompson** [comment]
Should installing it go in the readme?

**Comment by tescher** [comment]
Makes sense. Re-opening

**Comment by tescher** [comment]
moment-timezone also needed

**Comment by NigelKibodeaux** [comment]
dependencies should be added to the package.json. Matti fixed it in this commit so I'll close this ticket. https://github.com/codeforanchorage/realtime-bus-sms/commit/3ed682d9798460f84676b8674a398d8405b89f24
