### ISSUE TITLE
How to handle # in the bus stop id request

### ISSUE THREAD

**Issue by brendanbabb** [codeforanchorage/realtime-bus-sms#55]
I have seen one user send in #683 twice for the busstop id which doesn't return the bus stop info. Should we strip out # if it is the first character? Should we write a better description of just sending the number only.

**Comment by tescher** [comment]
I would strip it. More robust app then

**Comment by brendanbabb** [comment]
Done in https://github.com/codeforanchorage/realtime-bus-sms/pull/65
