### ISSUE TITLE
make the phone number clickable to send phone call (general) or text message. 

### ISSUE THREAD

**Issue by hansthompson** [codeforanchorage/realtime-bus-sms#60]
If we made a link that a phone would recognize to make a phonecall we could save the copy/paste step the user would use to text the number. 

<a href="tel:907-312-2060">Send a text to 907-312-2060</a>

I found this SO question on pre-populating the sms message if we ever want to get a step further.  

http://stackoverflow.com/questions/6480462/how-to-pre-populate-the-sms-body-text-via-an-html-link 

I'd make a commit myself but I don't want to break it while we are promoting it.

**Comment by brendanbabb** [comment]
Hans, that is a good idea. The challenge is not using a webpage to spam your friend's phone number. Balance has something similar: http://splash.codeforamerica.org/balance/english/ak/
I have been thinking about 2 factor authentication, maybe you send a PIN to enter. the person could still put your number to send you a text once. 

Also you can make a branch and do the changes there and when they look good do a Pull Request.

**Comment by hansthompson** [comment]
Lol, it looks like github recognized my html and didn't show it:

"<a href="tel:907-312-2060">Send a text to 907-312-2060</a>"

**Comment by hansthompson** [comment]
I'm not sure I know what you mean Brendan.

**Comment by brendanbabb** [comment]
Create a git branch and check it out. Then make your changes in the branch and test it and then push the branch changes up to the repo. And initiate a pull request. And someone will review it and merge it if everything looks good.

https://github.com/Kunena/Kunena-Forum/wiki/Create-a-new-branch-with-git-and-manage-branches

https://help.github.com/articles/using-pull-requests/

**Comment by tescher** [comment]
Is there a standard or recommended testing framework for Node.js? It would
be great to build some automated tests to run through before each PR. The
workflow is so limited and defined that it seems like that would be a
useful thing to have.

Tim Escher
tim@eschers.com
608-432-5799
