### ISSUE TITLE
Log resolved address from Google API

### ISSUE THREAD

**Issue by brendanbabb** [codeforanchorage/realtime-bus-sms#62]
In order to improve stop look ups by cross streets, look at the address it resolves too before returning lat and long if possible and record in the logs. Example: 5th and G Street returns different stops than 5th ave and G Street (which returns the Transit Center.) We can use to improve the directions to users for finding the stops they want or by adding Street suffixes if needed.

**Comment by brendanbabb** [comment]
Should we return the address it resolved in the list of stops?

**Comment by tescher** [comment]
Slack isn't letting me post for some reason. I'll look at these after
Christmas. Still stuck in Sydney at the moment.
