### ISSUE TITLE
Respond to HELP with instructions

### ISSUE THREAD

**Issue by NigelKibodeaux** [codeforanchorage/realtime-bus-sms#7]
The instructions can also be put on the page of the web interface

**Comment by NigelKibodeaux** [comment]
What are the instructions? I can make this happen pretty easily if someone wants to write them. @brendanbabb, you're good with words...

**Comment by brendanbabb** [comment]
I think the challenge with HELP is that it is intercepted by Twilio first and can't be rewritten or customized. https://www.twilio.com/help/faq/sms/can-you-customize-the-helpstop-messages-for-sms-filtering

So we can close this ticket if it sounds good.

**Comment by NigelKibodeaux** [comment]
Oh well
