### ISSUE TITLE
Log feedback to Slack

### ISSUE THREAD

**Issue by mattidupre** [codeforanchorage/realtime-bus-sms#72]
(API docs here)[https://api.slack.com/incoming-webhooks]

Pretty straightforward, could be nifty. I'm happy to take this one on when @NigelKibodeaux et. al. start refactoring the routes.

**Comment by NigelKibodeaux** [comment]
Good idea!

**Comment by joelpturman** [comment]
submitted a pull request for this issue. I realized I did not initialize or declare the new 'payload' variable. Could that present any issues?
