### ISSUE TITLE
Feedback Responses

### ISSUE THREAD

**Issue by tescher** [codeforanchorage/realtime-bus-sms#73]
One way to do it: In the e-mail to the bus account, include a link with a feedback-instance-dependent token (stored with the feedback log) that takes you to a web page where you can respond. If the feedback came in by SMS, the response will go by SMS. If the feedback came from the web page, we can add an optional e-mail field on the form and the response can be e-mailed back to the person. The token can be used to prevent just anyone from using the response web page.

**Comment by NigelKibodeaux** [comment]
That sounds good to me. The only downside I see I is that we'll have to store the user's phone number so we'll need to be careful with that data. 

Maybe we don't store it though and it could be encrypted in the emailed token... That would work fo the email address as well.

**Comment by tescher** [comment]
Would need to be a symmetric hash/crypto, which would go out on a public
email. I guess I'd rather keep any symmetric hashes internal to a
non-public log and use a one-way for the token. I'm paranoid I guess.

Tim Escher
tim@eschers.com
608-432-5799

**Comment by NigelKibodeaux** [comment]
Sure if it's more secure overall, that works for me. I was trying to stay
away from storing user data but emailing it around has risks too.

**Comment by NigelKibodeaux** [comment]
done
