### ISSUE TITLE
Change stats on logplot to use AST timezone

### ISSUE THREAD

**Issue by brendanbabb** [codeforanchorage/realtime-bus-sms#88]
Looks like the stats for unique users a day are based on the day ending at 4pm AST which would be UTC time. It gives stats for a 24 hour day, but it would be nice to have it for each AST day.

**Comment by markmeyerphoto** [comment]
Hi Brendan, I think this is a simple fix. The buckets will line up up with the dates in the proper time zone if you just shift the buckets +16 hours it will make the UTC times fall into Alaska time bins. 
I think this is the way to do it (and it seems to work), but my statistics are a little rusty:

` var bucket = (Math.floor(parseInt(point.date + (16*60*60)) / bucketWidth ) * bucketWidth) - (16*60*60); // shift the bucketing to account for UTC` 

I pushed a branch with the change.

**Comment by markmeyerphoto** [comment]
This failed to account for daylight savings time. I pushed a new fix that uses moment-timezone, which was already being used.

**Comment by tescher** [comment]
Can we use a Timezone environment variable? Otherwise when DST is over it
will probably be out of whack by an hour again.

Tim Escher
tim@eschers.com
608-432-5799

**Comment by markmeyerphoto** [comment]
The last patch used the config timezone variable and moment.tz to calculate the offset. Moment handles the daylight savings time offset. 

moment.tz("2016-11-06 01:59", "America/Anchorage")
 -> 2016-11-06T01:59:00-08:00

moment.tz("2016-11-06 02:00", "America/Anchorage"
-> 2016-11-06T02:00:00-09:00

**Comment by brendanbabb** [comment]
Thanks for all your work on this.

**Comment by tescher** [comment]
I think it should. It uses the moment-tz functionality rather than a
hard-coded offset.

Tim Escher
tim@eschers.com
608-432-5799
