### ISSUE TITLE
Remove emoticons and signatures from SMS input

### ISSUE THREAD

**Issue by tescher** [codeforanchorage/realtime-bus-sms#90]
Looks like this will work
https://www.npmjs.com/package/emoji-strip
and remove all input after the first \n

**Comment by markmeyerphoto** [comment]
#115 Should address some of this. It uses [https://www.npmjs.com/package/emoji-regex](https://www.npmjs.com/package/emoji-regex ), which is the package doing the heavy lifting behind emoji-strip. I am able to get a few emojis through, but it kills most of them.

**Comment by brendanbabb** [comment]
#115 is merged and fixed emoticons. Thanks @markmeyerphoto
